### ISSUE TITLE
Add back button 

### ISSUE THREAD

**Issue by pankajladhar** [pankajladhar/speedy-math#1]
Currently clicking on logo in quiz page goes to homepage, which is not intuitive enough on mobile.

**Comment by sureshHARDIYA** [comment]
@pankajladhar Good initiation to make it open source. I had in mind to make something similar for kids. Probably you could add roadmaps where you want to take this app and expect some PR from outside too.

**Comment by pankajladhar** [comment]
@sureshHARDIYA thanks for your valuble commit.

It you have any idea or feature to be built I will consider this or you can raise pull request

**Comment by sureshHARDIYA** [comment]
The main thing I would like to have is considering user profile so that user can store his/her profile and maintain a global leaderboard. 

Second is a time-based quiz. 
and many more. ...

**Comment by pankajladhar** [comment]
Fixed.
